{{- if .Values.ingress.enabled -}}
{{- $fullName := include "utils.fullname" . -}}
{{- $shortName := .Release.Name -}}
{{- $hasOAuth := index .Values "oauth2" "enabled" -}}
{{- $kubeVersion := include "utils.kubeVersion" . -}}

# ----------------------------------------------------------
# Expose all (protected) services through an ingress controller
# ----------------------------------------------------------
apiVersion: {{ include "utils.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "utils.labels" . | indent 4 }}
  annotations:
    {{ if $hasOAuth }}
    # Enable a application-specific auth proxy defined in the environment config...
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: 'X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Userid,X-Auth-Email,Authorization'
    {{- else }}
    # No application-specific authentication was found
    nginx.ingress.kubernetes.io/enable-global-auth: 'true'
    {{- end }}

  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:

# Bind to HTTPS port with the given certificates (if SSL enabled)
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  # Bind the routing rules to each host
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - {{- $path := "/api" -}}
            {{- $name := printf "%s-api" $fullName -}}            
            {{- include "utils.ingress.backend" (list . $path $name $kubeVersion) | indent 12 }}

  {{- end }}

---

{{ if $hasOAuth }}
# ----------------------------------------------------------
# For the localized oauth2 proxy, when enabled, we typically want to whitelist 
# some files and paths, from the authentication. This class serves that purpouse.
# ----------------------------------------------------------
apiVersion: {{ include "utils.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-oauth
  labels:
{{ include "utils.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
spec:
# Bind to HTTPS port with the given certificates
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  # Bind the routing rules to each host
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:          
          # Whitelist the oauth routes
          - {{- $path := "/oauth2" -}}
            {{- $name := printf "%s-oauth2" $shortName -}}            
            {{- include "utils.ingress.backend" (list . $path $name $kubeVersion) | indent 12 }}

  {{- end }}

{{- end }}


{{- end }}